"""Typed prediction evaluation and backtesting for BagelQuant."""

from .account import (
    AccountBacktestConfig,
    AccountBacktestResult,
    AccountStateCheckpoint,
    run_account_backtest,
)
from .benchmarks import benchmark_performance, build_universe_benchmark_returns
from .comparison import (
    ActualPerformancePath,
    PortfolioPathComparison,
    compare_portfolio_paths,
    run_actual_performance_path,
    run_continuous_target_path,
    run_total_return_weight_paths,
)
from .config import BacktestConfig, TransactionCostConfig
from .exceptions import (
    BacktestConfigError,
    BagelQuantBacktestError,
    InputValidationError,
)
from .factor import (
    PreparedFactorMarketData,
    factor_ic_decay_series,
    information_coefficients,
    materialize_factor_diagnostics,
    materialize_prediction_diagnostics,
    prediction_forward_returns,
    prepare_factor_market_data,
    run_prediction_evaluation,
)
from .path import (
    RESULT_SECTION_VERSION,
    RESULT_SECTIONS,
    PortfolioPathChunk,
    PortfolioPathIdentity,
    PortfolioStateCheckpoint,
    ResultSection,
    ResultSectionSpec,
    ResultWindow,
    compute_result_section,
    materialize_portfolio_path,
    portfolio_path_from_backtest,
    resume_portfolio_path,
)
from .pipeline import (
    compose_prediction,
    compose_processed_prediction,
    run_prediction_backtest,
)
from .policy import (
    AlphaPolicy,
    AlphaPolicyResult,
    AlphaStandardization,
    EvaluationAnchor,
    EvaluationFrequency,
    ExecutionPolicy,
    HolidayAdjustment,
    MissingSnapshotAction,
    ScheduledPrediction,
    ScheduledWeights,
    alpha_policies,
    execution_policies,
    resolve_alpha_policy,
    resolve_execution_policy,
)
from .portfolio import (
    EqualWeightPolicy,
    FloatMarketCapWeightPolicy,
    PredictionRegularizedOptimizerPolicy,
    TargetVolatilityPolicy,
    WeightBuild,
)
from .reporting import (
    ReportFigure,
    prediction_evaluation_report_figures,
    summary_report,
)
from .results import (
    BacktestResult,
    FactorEvaluationResult,
    PerformanceSummary,
    PredictionEvaluationResult,
    TransactionCostBreakdown,
)
from .returns import prepare_price_data
from .statistics import (
    OneSampleTest,
    cross_sectional_factor_returns,
    one_sample_t_test,
    quantile_rank_information_coefficients,
)
from .validation import (
    MonthlyIcObservation,
    TopNSelectionResult,
    ValidationObjective,
    ValidationScore,
    score_ic_validation,
    score_top_n_performance,
    select_top_n_stable,
    top_n_monthly_performance,
)

__all__ = [
    "RESULT_SECTIONS",
    "RESULT_SECTION_VERSION",
    "AccountBacktestConfig",
    "AccountBacktestResult",
    "AccountStateCheckpoint",
    "ActualPerformancePath",
    "AlphaPolicy",
    "AlphaPolicyResult",
    "AlphaStandardization",
    "BacktestConfig",
    "BacktestConfigError",
    "BacktestResult",
    "BagelQuantBacktestError",
    "EqualWeightPolicy",
    "EvaluationAnchor",
    "EvaluationFrequency",
    "ExecutionPolicy",
    "FactorEvaluationResult",
    "FloatMarketCapWeightPolicy",
    "HolidayAdjustment",
    "InputValidationError",
    "MissingSnapshotAction",
    "MonthlyIcObservation",
    "OneSampleTest",
    "PerformanceSummary",
    "PortfolioPathChunk",
    "PortfolioPathComparison",
    "PortfolioPathIdentity",
    "PortfolioStateCheckpoint",
    "PredictionEvaluationResult",
    "PredictionRegularizedOptimizerPolicy",
    "PreparedFactorMarketData",
    "ReportFigure",
    "ResultSection",
    "ResultSectionSpec",
    "ResultWindow",
    "ScheduledPrediction",
    "ScheduledWeights",
    "TargetVolatilityPolicy",
    "TopNSelectionResult",
    "TransactionCostBreakdown",
    "TransactionCostConfig",
    "ValidationObjective",
    "ValidationScore",
    "WeightBuild",
    "alpha_policies",
    "benchmark_performance",
    "build_universe_benchmark_returns",
    "compare_portfolio_paths",
    "compose_prediction",
    "compose_processed_prediction",
    "compute_result_section",
    "cross_sectional_factor_returns",
    "execution_policies",
    "factor_ic_decay_series",
    "information_coefficients",
    "materialize_factor_diagnostics",
    "materialize_portfolio_path",
    "materialize_prediction_diagnostics",
    "one_sample_t_test",
    "portfolio_path_from_backtest",
    "prediction_evaluation_report_figures",
    "prediction_forward_returns",
    "prepare_factor_market_data",
    "prepare_price_data",
    "quantile_rank_information_coefficients",
    "resolve_alpha_policy",
    "resolve_execution_policy",
    "resume_portfolio_path",
    "run_account_backtest",
    "run_actual_performance_path",
    "run_continuous_target_path",
    "run_prediction_backtest",
    "run_prediction_evaluation",
    "run_total_return_weight_paths",
    "score_ic_validation",
    "score_top_n_performance",
    "select_top_n_stable",
    "summary_report",
    "top_n_monthly_performance",
]
