"""Standalone Alpha, portfolio-weight and transaction-plan evaluation."""

from .allocation import IntegerTargetAllocation, allocate_integer_positions
from .benchmarks import (
    benchmark_performance,
    build_universe_benchmark_returns,
    compare_portfolio_to_benchmarks,
)
from .config import (
    TransactionCostConfig,
)
from .diagnostics import (
    aggregate_exposures,
    alpha_evaluation_contract,
    annualized_ratio,
    horizon_tables,
    model_horizon_correlations,
    signal_coverage,
    stability_tables,
)
from .evaluation import (
    EvaluationResult,
    evaluate_alpha,
    evaluate_weights,
    return_statistics,
)
from .exceptions import (
    BacktestConfigError,
    BagelQuantBacktestError,
    InputValidationError,
)
from .execution_evaluation import (
    ExecutionConfig,
    ExecutionCostQuote,
    ExecutionCostRule,
    ExecutionEvaluationResult,
    ExecutionStateCheckpoint,
    evaluate_execution,
    execution_stress_scenarios,
    load_checkpoint,
    merge_execution_tables,
    run_execution_from_weights,
    save_checkpoint,
    summarize_transaction_pnl,
)
from .factor_analysis import (
    factor_return_correlation,
    holdings_factor_exposure,
    incremental_ic_summary,
    monthly_rank_returns,
    partial_rank_ic,
)
from .horizon import (
    DAILY_ALPHA_RETURN_LAGS,
    DAILY_BOOK_LEAD_LAGS,
    DAILY_BUCKET_WINDOWS,
    DAILY_CUMULATIVE_WINDOWS,
    DAILY_ROLLING_IC_OBSERVATIONS,
    DAILY_SESSION_WINDOWS,
    DAILY_SUMMARY_AUTOCORRELATION_LAGS,
    SIGNAL_PERSISTENCE_HORIZONS,
    HACMeanTest,
    PredictionHorizonDiagnostics,
    SessionWindow,
    benjamini_hochberg,
    build_statistical_inference,
    centered_rank_book_weights,
    gross_one_tail_weights,
    hac_mean_test,
    implied_signal_half_life,
    non_overlapping_cohort_statistics,
    quantile_curve_structure,
    rolling_window_information_coefficients,
    signal_rank_persistence,
    summarize_signal_persistence,
    summarize_window_ic,
    window_book_returns,
    window_factor_returns,
    window_information_coefficients,
    window_quantile_forward_returns,
    window_tail_returns,
)
from .periods import (
    aggregate_saved_window,
    slice_primitives,
)
from .portfolio_mechanics import (
    WeightStateCheckpoint,
    build_alpha_weights,
)
from .research_comparison import (
    account_fill_turnover,
    common_alpha_ic,
)
from .research_statistics import (
    capacity_participation,
    common_sample_comparison,
    deflated_sharpe,
    library_endpoint_tests,
)
from .returns import (
    drawdown,
    prepare_price_data,
)
from .risk import (
    CrossSectionalRiskFit,
    RollingRiskProfile,
    fit_risk_factor_returns,
    industry_exposure_strength,
    link_risk_contributions,
    residualize_risk_descriptor,
    risk_interval_returns,
    rolling_risk_profile,
    standardize_risk_descriptor,
)
from .runtime import (
    BTExecutionOptions,
    run_evaluation_batch,
)
from .sample import SAMPLE_POLICY, evaluation_sample
from .statistics import (
    OneSampleTest,
    annualized_return,
    cross_sectional_factor_returns,
    one_sample_t_test,
    quantile_rank_information_coefficients,
    return_metrics,
)
from .store import (
    BTStore,
    evaluation_identity,
)

__all__ = [
    "DAILY_ALPHA_RETURN_LAGS",
    "DAILY_BOOK_LEAD_LAGS",
    "DAILY_BUCKET_WINDOWS",
    "DAILY_CUMULATIVE_WINDOWS",
    "DAILY_ROLLING_IC_OBSERVATIONS",
    "DAILY_SESSION_WINDOWS",
    "DAILY_SUMMARY_AUTOCORRELATION_LAGS",
    "SAMPLE_POLICY",
    "SIGNAL_PERSISTENCE_HORIZONS",
    "BTExecutionOptions",
    "BTStore",
    "BacktestConfigError",
    "BagelQuantBacktestError",
    "CrossSectionalRiskFit",
    "EvaluationResult",
    "ExecutionConfig",
    "ExecutionCostQuote",
    "ExecutionCostRule",
    "ExecutionEvaluationResult",
    "ExecutionStateCheckpoint",
    "HACMeanTest",
    "InputValidationError",
    "IntegerTargetAllocation",
    "OneSampleTest",
    "PredictionHorizonDiagnostics",
    "RollingRiskProfile",
    "SessionWindow",
    "TransactionCostConfig",
    "WeightStateCheckpoint",
    "account_fill_turnover",
    "aggregate_exposures",
    "aggregate_saved_window",
    "allocate_integer_positions",
    "alpha_evaluation_contract",
    "annualized_ratio",
    "annualized_return",
    "benchmark_performance",
    "benjamini_hochberg",
    "build_alpha_weights",
    "build_statistical_inference",
    "build_universe_benchmark_returns",
    "capacity_participation",
    "centered_rank_book_weights",
    "common_alpha_ic",
    "common_sample_comparison",
    "compare_portfolio_to_benchmarks",
    "cross_sectional_factor_returns",
    "deflated_sharpe",
    "drawdown",
    "evaluate_alpha",
    "evaluate_execution",
    "evaluate_weights",
    "evaluation_identity",
    "evaluation_sample",
    "execution_stress_scenarios",
    "factor_return_correlation",
    "fit_risk_factor_returns",
    "gross_one_tail_weights",
    "hac_mean_test",
    "holdings_factor_exposure",
    "horizon_tables",
    "implied_signal_half_life",
    "incremental_ic_summary",
    "industry_exposure_strength",
    "library_endpoint_tests",
    "link_risk_contributions",
    "load_checkpoint",
    "merge_execution_tables",
    "model_horizon_correlations",
    "monthly_rank_returns",
    "non_overlapping_cohort_statistics",
    "one_sample_t_test",
    "partial_rank_ic",
    "prepare_price_data",
    "quantile_curve_structure",
    "quantile_rank_information_coefficients",
    "residualize_risk_descriptor",
    "return_metrics",
    "return_statistics",
    "risk_interval_returns",
    "rolling_risk_profile",
    "rolling_window_information_coefficients",
    "run_evaluation_batch",
    "run_execution_from_weights",
    "save_checkpoint",
    "signal_coverage",
    "signal_rank_persistence",
    "slice_primitives",
    "stability_tables",
    "standardize_risk_descriptor",
    "summarize_signal_persistence",
    "summarize_transaction_pnl",
    "summarize_window_ic",
    "window_book_returns",
    "window_factor_returns",
    "window_information_coefficients",
    "window_quantile_forward_returns",
    "window_tail_returns",
]
